# Generated by Django 5.2 on 2025-05-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(max_length=100)),
                ('building_number', models.CharField(max_length=10)),
                ('room_number', models.CharField(max_length=10)),
            ],
        ),
    ]
