# Generated by Django 5.2 on 2025-05-13 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamWeb', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ExamWeb.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='proctor',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='ExamWeb.exam'),
        ),
    ]
